let resumeData = {
	firstName: 'Scott',
	lastName: 'Whitney',
	role: 'Full Stack Developer & EdTech Engineer',
	linkedIn: 'https://www.linkedin.com/in/scott-whitney/',
	country: 'USA',
	state: 'TX',
	city: 'Nacogdoches',
	zipcode: '75965',
	street: 'Heather',
	address: '1816',
	textnumber: '936-615-3285',
	voicenumber: '936-463-7579',
	email: 'whitneyscottasl@gmail.com',
	testimonial1: 'Dr. Whitney`s use of technology to enhance learning  experiences hasbeen of benefit to students and faculty alike.',
	testifier1: 'Janet Kamps',
	testimonial2: 'While at SFA, I have observed a very committed and competent faculty member who has put in the time, provided the leadership and stability necssary to grow a very strong, thriving program for prospective teachers for the deaf and hard of hearing.',
	testifier2: 'Paige Mask',
	proficient: 'database and javascript engineer',
	enthusiasm: 'aesthetics and efficient code',
	experience:
		'developing applications for American Sign Language instruction using multiple languages and technologies',
	priority:
		'the impact of small acts, small details and kind words on each individual life',
	drivingForce:
		'making a positive difference by applying technology to the challenges in the world - especially the barriers faced by the Deaf community',
	univ1:'North Park College',
	degree1: 'BA',
	major1: 'Biology',
	details1: 'Started as a pre-medicine major, but switched to research. Prepared for a career in neuroscience.',
	gradmo1: 'May',
	gradyr1: '1989',
	univ2:'Illinois State University',
	degree2: 'MA',
	details2: 'Experienced a progressive hearing loss with resultant communicaton barriers. Learned American Sign Language in order to remove the barriers while acquiring a marketable degree.',
	gradmo2: 'July',
	gradyr2: '1994',
	major2: 'Special Education - Emphasis in Deaf Education',
	univ3:'Lamar University',
	degree3: 'EdD',
	major3: 'Deaf Education and Deaf Studies',
	details3: 'The dissertation reported research on using a panoramic adventure game as a teaching tool. In order to study the game, I scripted the interactive elements using Adobe Director Lingo and resulted in a Shockwave app.',
	gradmo3: 'May',
	gradyr3: '2001',
	skillsummary:'Various projects spanning a wide range of requirements have resulted in the acquisition of skills necessary for Full Stack development:',
	skill1:'PHP',
	skill1lvl:'60%',
	work1Loc:'Stephen F. Austin State University',
	work1Role1: 'Associate Professor',
	work1Role2:'Program Director - 12 years',
	work1Start:'2002',
	work1End:'Present',
	work1Summary:'Lead the development and implementation of online courses. Developed ASLexpress software to increase foreign language study efficiency. Created an app to recognize American Sign Language handshapes.'
	};
export default resumeData;
